// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoraK30hLaLOVcD-y0Mnz7dnWn1eTmqR8',
    appId: '1:789975241505:web:38e20da65b96580ab46460',
    messagingSenderId: '789975241505',
    projectId: 'jokesapp213233',
    authDomain: 'jokesapp213233.firebaseapp.com',
    storageBucket: 'jokesapp213233.firebasestorage.app',
    measurementId: 'G-KZXBBNQWYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRlEG8XMo3Dtm2VqaepffNPtPqH47918',
    appId: '1:789975241505:android:5f0e958da80ea69ab46460',
    messagingSenderId: '789975241505',
    projectId: 'jokesapp213233',
    storageBucket: 'jokesapp213233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqSqM6eR-UIS3Up32kMPPKTDyHj9d60ds',
    appId: '1:789975241505:ios:b57994a64024ab50b46460',
    messagingSenderId: '789975241505',
    projectId: 'jokesapp213233',
    storageBucket: 'jokesapp213233.firebasestorage.app',
    iosBundleId: 'com.example.mis2',
  );
}
